const barcelona = {
    titulo: 'Descubre Barcelona: La joya de Cataluña.',
    precio: ' El precio promocional por hoy es de 500 euros',
    subtitulo: 'Sumérgete en la historia, cultura y belleza de esta vibrante ciudad.',
    parrafo: 'Bienvenidos a Barcelona, una ciudad cautivadora que combina a la perfección su rica  herencia histórica con un estilo de vida moderno y cosmopolita. Conocida por su arquitectura única, playas doradas y una escena artística y culinaria animada, Barcelona es un destino turístico incomparable.<br> <br> La ciudad es el hogar de algunas de las obras maestras arquitectónicas más emblemáticas de Antoni Gaudí, como la Sagrada Familia, el Parque Güell y la Casa Batlló, que cautivan a los visitantes con sus formas surrealistas y colores vibrantes.<br><br> Sumérgete en el bullicioso corazón de la ciudad explorando Las Ramblas, una icónica avenida peatonal llena de vida, tiendas, artistas callejeros y restaurantes. Descubre el Barrio Gótico, un laberinto de calles estrechas y plazas adoquinadas que te transportarán a la Barcelona medieval.<br><br> La influencia del arte y la cultura también se refleja en los numerosos museos, galerías y eventos culturales de la ciudad, como el Museo Picasso y el MACBA (Museo de Arte Contemporáneo de Barcelona).<br><br> Barcelona ofrece una mezcla única de experiencias gastronómicas, desde los mercados tradicionales como La Boquería hasta los innovadores restaurantes que destacan la cocina catalana. La ciudad es famosa por su animada vida nocturna, donde los bares y clubes te invitan a disfrutar de la música, la danza y la diversión hasta altas horas de la madrugada.<br><br> Con su ubicación privilegiada junto al mar Mediterráneo, Barcelona también cuenta con extensas playas como la Barceloneta, donde puedes relajarte bajo el sol, disfrutar de deportes acuáticos o simplemente pasear por el paseo marítimo.<br><br> En resumen, Barcelona ofrece una experiencia única que combina historia, arte, gastronomía y ocio, convirtiéndola en un destino imprescindible para los viajeros que buscan una escapada inolvidable.',
};

const roma = {
    titulo: 'Roma: Tesoros eternos en la Ciudad Eterna.',
    precio: ' El precio promocional por hoy es de 400 euros',
    subtitulo: 'Sumérgete en la grandeza histórica, el arte y la cultura de la capital italiana.',
    parrafo: 'Bienvenidos a Roma, una ciudad que respira historia en cada rincón y que te transporta a través de los siglos con su impresionante patrimonio arquitectónico y cultural. <br> <br>Conocida por ser la cuna de la civilización romana y del Imperio, Roma ofrece una experiencia única que combina la majestuosidad de sus antiguos monumentos con la vitalidad de la vida contemporánea.<br><br> El Coliseo, un ícono imponente de la Roma antigua, te sumerge en la grandeza de los espectáculos gladiatorios. Junto con el Foro Romano y el Palatino, forman un conjunto arqueológico que te transporta al corazón de la vida cotidiana en la antigua Roma.<br><br> La Ciudad del Vaticano, con la majestuosa Basílica de San Pedro y los Museos Vaticanos, es un centro espiritual y artístico que alberga algunas de las obras maestras más importantes de la historia del arte, como la Capilla Sixtina de Miguel Ángel.<br><br> Pasear por las encantadoras calles adoquinadas de Roma te lleva al pasado, especialmente en barrios como Trastevere, donde descubrirás plazas pintorescas y auténticas trattorias que sirven deliciosa cocina italiana.<br><br> La Fontana di Trevi, una de las fuentes más famosas del mundo, es un lugar mágico para arrojar una moneda y hacer un deseo, mientras que la Plaza de España y sus escalinatas ofrecen una vista impresionante de la ciudad.<br><br> Roma es también un paraíso gastronómico, donde puedes disfrutar de auténtica pasta, pizza y gelato en restaurantes tradicionales o en acogedores cafés al aire libre.<br><br> La energía y vitalidad de Roma se reflejan en su gente apasionada y en su animada escena cultural. Ya sea explorando sus museos, asistiendo a eventos culturales o simplemente paseando por sus plazas históricas, cada rincón de la Ciudad Eterna cuenta una historia fascinante.<br><br> En resumen, Roma es un tesoro histórico y cultural que ofrece una experiencia única y cautivadora, fusionando la grandeza del pasado con la vitalidad del presente.',
};

const parís = {
    titulo: 'París: La Ciudad de la luz y el Romance.',
    precio: ' El precio promocional por hoy es de 550 euros',
    subtitulo: 'Explora la elegancia, la cultura y el encanto de la capital francesa.',
    parrafo: 'Bienvenidos a París, una metrópolis que celebra la belleza, el arte y el estilo de vida sofisticado.<br><br> La Torre Eiffel, símbolo indiscutible de París, domina el horizonte y ofrece vistas panorámicas espectaculares de la ciudad. Pasear por la orilla del río Sena, flanqueada por majestuosos puentes, es una experiencia romántica que revela la arquitectura clásica y los encantadores cafés a lo largo de sus orillas.<br><br> Los Campos Elíseos, una amplia avenida arbolada, te lleva desde el Arco de Triunfo hasta el Jardín de las Tullerías, creando un espectacular bulevar lleno de tiendas de lujo, teatros y cafés elegantes.<br><br> El Louvre, el museo más grande del mundo, alberga una vasta colección de obras maestras, incluida la famosa Mona Lisa. El arte y la cultura también se despliegan en otros lugares notables como el Musée d\'Orsay y el Centre Pompidou.<br><br> Montmartre, con su bohemia y la Basílica del Sagrado Corazón, te transporta a un París lleno de encanto y creatividad. Las estrechas calles adoquinadas y las plazas animadas hacen de este barrio un lugar pintoresco y lleno de historia.<br><br> La gastronomía parisina es famosa en todo el mundo, desde la haute cuisine en restaurantes estrellados hasta los acogedores bistros que sirven delicias locales. Un paseo por los mercados callejeros te permitirá disfrutar de quesos, vinos y baguettes frescas que son parte integral de la experiencia parisina.<br><br> París, con su atmósfera romántica y su estatus como centro cultural global, es un destino que combina la grandeza histórica con la modernidad, ofreciendo a los visitantes una experiencia única e inolvidable. Cada calle, cada rincón, está impregnado de arte, historia y ese inconfundible encanto parisino.',
};

const londres = {
    titulo: 'Londres: Descubre la magia de la Ciudad del Támesis.',
    precio: ' El precio promocional por hoy es de 600 euros',
    subtitulo: 'Sumérgete en la historia, la diversidad y la energía de la capital británica.',
    parrafo: 'Bienvenidos a Londres, una ciudad cosmopolita que fusiona su rica herencia histórica con la modernidad vibrante. Con una mezcla única de tradición y innovación, Londres ofrece una experiencia diversa que atrae a visitantes de todo el mundo.<br><br> El Palacio de Buckingham y la Casa del Parlamento con el icónico Big Ben son hitos emblemáticos que reflejan la grandeza de la historia británica. El río Támesis, que serpentea a través de la ciudad, ofrece vistas espectaculares y cruceros relajantes.<br><br> Los museos de clase mundial, como el Museo Británico, la Galería Nacional y el Museo de Historia Natural, albergan tesoros culturales y científicos que cautivan a amantes del arte, la historia y la ciencia.<br><br> El bullicioso mercado de Camden, la elegante Oxford Street y el encantador Notting Hill son solo algunas de las muchas áreas comerciales que reflejan la diversidad de la escena comercial de Londres. Los mercados locales, como Borough Market, ofrecen una deliciosa variedad de alimentos frescos y gourmet.<br><br> Los parques reales, como Hyde Park y Regents Park, proporcionan espacios verdes expansivos donde los londinenses y los visitantes pueden relajarse, hacer picnics y disfrutar de actividades al aire libre.<br><br> La Torre de Londres, con su historia medieval y las Joyas de la Corona, ofrece una visión fascinante del pasado. El moderno London Eye proporciona una vista panorámica impresionante del horizonte londinense.<br><br> Londres es también conocida por su escena teatral en el West End, que presenta producciones teatrales de clase mundial y musicales que atraen a amantes del espectáculo de todas partes.<br><br> La diversidad gastronómica de Londres es un reflejo de su multiculturalidad, con una amplia variedad de restaurantes que ofrecen cocina de todo el mundo. Los pubs tradicionales, además, son lugares acogedores donde puedes probar auténticas cervezas británicas.<br><br> En resumen, Londres es una ciudad vibrante que combina historia, cultura, modernidad y diversidad. Cada vecindario tiene su propio carácter único, contribuyendo a la riqueza y variedad de experiencias que ofrece esta metrópolis global.',
};

export {
    barcelona,
    roma,
    parís,
    londres,
};